### ISSUE TITLE
Query on code contribution

### ISSUE THREAD

**Issue by shonjs** [hyperledgerkochi/KochiOrgBook#15]
We had started exploring on a platform which would help developers to issue and verify credentials, based on aries protocols. We did some experimenting but it got paused in between because of other priorities that came up. I think it is similar to the KOB connector and the overall architecture also seems somewhat aligned. Here is what we have currently :
- APIs for issuance (implicit connections via email), verification. API sits in front of and works with [aries acapy](https://github.com/hyperledger/aries-cloudagent-python) (which resolves on indy ledger)
- Mobile wallet which can make connections (with other aries agents), requests credential, hold credentials, present proof, cloud backup (forked and extended from [AXMA](https://github.com/hyperledger/aries-mobileagent-xamarin)).
- Deploys on docker, single user cloud wallet (agent) (can be backed up), mediator for the mobile wallet, tested with local indy ledger and sovrin builder net, works end to end (happy path)

I would like to know if this seems interesting and can add value here. If so we would be happy to clean up the code some and contribute it.

**Comment by panickervinod** [comment]
. @shonjs sounds good to me. @asa1997 @sumodgeorge  I think we should schedule next level discussion on this
